from sqlalchemy import Column, Integer, String, Float, ForeignKey, DateTime, JSON, Boolean
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from core.database import Base

class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    profile = relationship("Profile", back_populates="user", uselist=False)
    portfolios = relationship("Portfolio", back_populates="user")
    simulations = relationship("Simulation", back_populates="user")

class Profile(Base):
    __tablename__ = "profiles"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), unique=True)
    
    # ML & Behavioral Scoring
    risk_capacity_score = Column(Float, default=50.0)
    risk_tolerance_score = Column(Float, default=50.0)
    overall_risk_score = Column(Float, default=50.0)
    investment_horizon_months = Column(Integer, default=60)
    
    user = relationship("User", back_populates="profile")

class Asset(Base):
    """Tracks tradable assets (e.g., ETFs, Stocks, Crypto)"""
    __tablename__ = "assets"
    id = Column(Integer, primary_key=True, index=True)
    ticker = Column(String, unique=True, index=True, nullable=False)
    name = Column(String, nullable=False)
    asset_class = Column(String, nullable=False) # e.g., 'Equity', 'Bond', 'Crypto'
    
    market_data = relationship("MarketData", back_populates="asset")
    portfolio_allocations = relationship("PortfolioAsset", back_populates="asset")

class MarketData(Base):
    """Time-series data for ML training and CVaR optimization"""
    __tablename__ = "market_data"
    id = Column(Integer, primary_key=True, index=True)
    asset_id = Column(Integer, ForeignKey("assets.id"))
    date = Column(DateTime(timezone=True), nullable=False)
    close_price = Column(Float, nullable=False)
    adjusted_close = Column(Float, nullable=False)
    volume = Column(Integer, default=0)
    
    asset = relationship("Asset", back_populates="market_data")

class Portfolio(Base):
    """User portfolios generated by the optimizer"""
    __tablename__ = "portfolios"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    name = Column(String, default="Core AI Portfolio")
    target_return = Column(Float)
    target_risk = Column(Float) # CVaR or Volatility metric
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    user = relationship("User", back_populates="portfolios")
    assets = relationship("PortfolioAsset", back_populates="portfolio")

class PortfolioAsset(Base):
    """The specific percentage allocation of an asset within a portfolio"""
    __tablename__ = "portfolio_assets"
    id = Column(Integer, primary_key=True, index=True)
    portfolio_id = Column(Integer, ForeignKey("portfolios.id"))
    asset_id = Column(Integer, ForeignKey("assets.id"))
    weight = Column(Float, nullable=False) # E.g., 0.40 for 40%
    
    portfolio = relationship("Portfolio", back_populates="assets")
    asset = relationship("Asset", back_populates="portfolio_allocations")

class Simulation(Base):
    """Historical record of Monte Carlo runs for the user dashboard"""
    __tablename__ = "simulations"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    ticker = Column(String, nullable=False)
    days_simulated = Column(Integer)
    current_price = Column(Float)
    median_projection = Column(Float)
    bull_case_95th = Column(Float)
    bear_case_5th = Column(Float)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    user = relationship("User", back_populates="simulations")

class ModelRegistry(Base):
    """Tracks deployed ML models to prevent silent failures and monitor drift"""
    __tablename__ = "model_registry"
    id = Column(Integer, primary_key=True, index=True)
    model_name = Column(String, nullable=False) # e.g., 'RandomForest_RiskScorer_v1'
    version = Column(String, nullable=False)
    metrics = Column(JSON) # e.g., {"MSE": 0.04, "Sharpe": 1.2}
    is_active = Column(Boolean, default=False)
    deployed_at = Column(DateTime(timezone=True), server_default=func.now())